export const GET_POSTS_STARTED = "GET_POSTS_STARTED";
export const GET_POSTS_SUCCESS = "GET_POSTS_SUCCESS";
export const GET_POSTS_FAILED = "GET_POSTS_FAILED";

export const SAVE_POST_STARTED = "SAVE_POST_STARTED";
export const SAVE_POST_SUCCESS = "SAVE_POST_SUCCESS";
export const SAVE_POST_FAILED = "SAVE_POST_FAILED";

export const LIKE_POST_STARTED = "LIKE_POST_STARTED";
export const LIKE_POST_SUCCESS = "LIKE_POST_SUCCESS";
export const LIKE_POST_FAILED = "LIKE_POST_FAILED";

export const UNLIKE_POST_STARTED = "UNLIKE_POST_STARTED";
export const UNLIKE_POST_SUCCESS = "UNLIKE_POST_SUCCESS";
export const UNLIKE_POST_FAILED = "UNLIKE_POST_FAILED";

export const GET_COMMENTS_STARTED = "GET_COMMENTS_STARTED";
export const GET_COMMENTS_SUCCESS = "GET_COMMENTS_SUCCESS";
export const GET_COMMENTS_FAILED = "GET_COMMENTS_FAILED";

export const SAVE_COMMENT_STARTED = "SAVE_COMMENT_STARTED";
export const SAVE_COMMENT_SUCCESS = "SAVE_COMMENT_SUCCESS";
export const SAVE_COMMENT_FAILED = "SAVE_COMMENT_FAILED";

export const CLEAR_COMMENTS = "CLEAR_COMMENTS";