export const SET_CURRENT_USER_STARTED = "SET_CURRENT_USER_STARTED";
export const SET_CURRENT_USER_SUCCESS = "SET_CURRENT_USER_SUCCESS";
export const SET_CURRENT_USER_FAILED = "SET_CURRENT_USER_FAILED";
export const SIGN_OUT_USER_SUCCESS = "SIGN_OUT_USER_SUCCESS";



