export const GET_COURSES_STARTED = "GET_COURSES_STARTED";
export const GET_COURSES_SUCCESS = "GET_COURSES_SUCCESS";
export const GET_COURSES_FAILED = "GET_COURSES_FAILED";

export const GET_CREATED_COURSES_STARTED = "GET_CREATED_COURSES_STARTED";
export const GET_CREATED_COURSES_SUCCESS = "GET_CREATED_COURSES_SUCCESS";
export const GET_CREATED_COURSES_FAILED = "GET_CREATED_COURSES_FAILED";

export const GET_FOLLOWING_COURSES_STARTED = "GET_FOLLOWING_COURSES_STARTED";
export const GET_FOLLOWING_COURSES_SUCCESS = "GET_FOLLOWING_COURSES_SUCCESS";
export const GET_FOLLOWING_COURSES_FAILED = "GET_FOLLOWING_COURSES_FAILED";

export const FOLLOW_COURSE_STARTED = "FOLLOW_COURSE_STARTED";
export const FOLLOW_COURSE_SUCCESS = "FOLLOW_COURSE_SUCCESS";
export const FOLLOW_COURSE_FAILED = "FOLLOW_COURSE_COURSES_FAILED";

export const UNFOLLOW_COURSE_STARTED = "UNFOLLOW_COURSE_STARTED";
export const UNFOLLOW_COURSE_SUCCESS = "UNFOLLOW_COURSE_SUCCESS";
export const UNFOLLOW_COURSE_FAILED = "UNFOLLOW_COURSE_FAILED";

export const CREATE_COURSE_STARTED = "CREATE_COURSE_STARTED";
export const CREATE_COURSE_SUCCESS = "CREATE_COURSE_SUCCESS";
export const CREATE_COURSE_FAILED = "CREATE_COURSE_FAILED";

export const DELETE_COURSE_STARTED = "DELETE_COURSE_STARTED";
export const DELETE_COURSE_SUCCESS = "DELETE_COURSE_SUCCESS";
export const DELETE_COURSE_FAILED = "DELETE_COURSE_FAILED";